### ISSUE TITLE
"TypeError: urlopen() got an unexpected keyword argument 'context'" when building on Debian Jessie

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-build#27] opened 2017-04-10 19:42 UTC
Workaround : edit kiwix-build.py to remove the "context" argument when urlopen() is called (line 418).

It seems to come from the version of python3 distributed with debian jessie (3.4.2-2)

**Comment by kelson42** [comment] 2017-04-16 09:15
Seems to be a duplicate of #31 (or the other way around, but there is more information in #31)

**Closed by kelson42** 2017-04-16 09:15 UTC

**Comment by julianharty** [comment] 2017-04-17 07:38
I don't mind which issue (this or https://github.com/kiwix/kiwix-build/issues/31) is used to track the issue and how we resolve it. I opened 31 because I didn't see this one (even though I looked) a phrase I remember from my childhood is "I can't see for looking".
