### ISSUE TITLE
  test libzim : ERROR

### ISSUE THREAD

**Issue by diegoroversi** [kiwix/kiwix-build#481] opened 2021-04-05 18:39 UTC
Fail to build.  Tested on armhf debian stable, with the latest git version (commit b068b277f10bdd870d7b8ede94312e7e0587727a).

Output:

```
(src) diego@scw-19c522:~/src/kiwix-build$ kiwix-build
[INSTALL PACKAGES]
 - automake : SKIP
 - libtool : SKIP
 - cmake : SKIP
 - git : SKIP
 - subversion : SKIP
 - ccache : SKIP
 - pkg-config : SKIP
 - gcc : SKIP
 - autopoint : SKIP
 - libbz2-dev : SKIP
 - libmagic-dev : SKIP
 - zlib1g-dev : SKIP
 - uuid-dev : SKIP
 - libmicrohttpd-dev : SKIP
SKIP, No package to install.
[...]


build icu4c (native_dyn):
  configure icu4c : SKIP
  compile icu4c : SKIP
  install icu4c : SKIP
build libzim (native_dyn):
  configure libzim : SKIP
  compile libzim : OK (0.1s)
  test libzim : ERROR
run command 'meson test --verbose -t 8'   
current directory is '/home/diego/src/kiwix-build/BUILD_native_dyn/libzim'
env is :
  SHELL : '/bin/bash'
  LANGUAGE : 'en_US.UTF-8'
  PWD : '/home/diego/src/kiwix-build'
  LOGNAME : 'diego'
  TZ : 'CET'
  HOME : '/home/diego'
  LANG : 'en_US.UTF-8'
  LS_COLORS : 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
  VIRTUAL_ENV : '/home/diego/src'
  TERM : 'screen.xterm-256color'
  USER : 'diego'
  SHLVL : '1'
  LD_LIBRARY_PATH : '/home/diego/src/kiwix-build/BUILD_native_dyn/INSTALL/lib/arm-linux-gnueabihf/:/home/diego/src/kiwix-build/BUILD_native_dyn/INSTALL/lib:/home/diego/src/kiwix-build/BUILD_native_dyn/INSTALL/lib/arm-linux-gnueabihf'
  PS1 : '(src) ${debian_chroot:+($debian_chroot)}\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\$ '
  LC_ALL : 'en_US.UTF-8'
  PATH : '/home/diego/src/kiwix-build/BUILD_native_dyn/INSTALL/bin:/home/diego/src/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games'
  MAIL : '/var/mail/diego'
  SKIP_BIG_MEMORY_TEST : '1'
  OLDPWD : '/home/diego/src'
  _ : '/home/diego/src/bin/kiwix-build'   
  PKG_CONFIG_PATH : ':/home/diego/src/kiwix-build/BUILD_native_dyn/INSTALL/lib/arm-linux-gnueabihf/pkgconfig'
  QMAKE_CXXFLAGS : '-I/home/diego/src/kiwix-build/BUILD_native_dyn/INSTALL/include '
  CPPFLAGS : '-I/home/diego/src/kiwix-build/BUILD_native_dyn/INSTALL/include '
  QMAKE_LFLAGS : '-L/home/diego/src/kiwix-build/BUILD_native_dyn/INSTALL/lib -L/home/diego/src/kiwix-build/BUILD_native_dyn/INSTALL/lib/arm-linux-gnueabihf '
  LDFLAGS : '-L/home/diego/src/kiwix-build/BUILD_native_dyn/INSTALL/lib -L/home/diego/src/kiwix-build/BUILD_native_dyn/INSTALL/lib/arm-linux-gnueabihf '
ninja: Entering directory `/home/diego/src/kiwix-build/BUILD_native_dyn/libzim'
ninja: no work to do.
Running main() from ../../SOURCE/libzim/subprojects/googletest-release-1.8.1/googletest/src/gtest_main.cc
[==========] Running 4 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from CacheTest
[ RUN      ] CacheTest.SimplePut
[       OK ] CacheTest.SimplePut (0 ms)   
[ RUN      ] CacheTest.OverwritingPut
[       OK ] CacheTest.OverwritingPut (0 ms)
[ RUN      ] CacheTest.MissingValue
[       OK ] CacheTest.MissingValue (0 ms)
[----------] 3 tests from CacheTest (1 ms total)

[----------] 1 test from CacheTest1
[ RUN      ] CacheTest1.KeepsAllValuesWithinCapacity
[       OK ] CacheTest1.KeepsAllValuesWithinCapacity (2 ms)
[----------] 1 test from CacheTest1 (2 ms total)
[----------] Global test environment tear-down
[==========] 4 tests from 2 test cases ran. (3 ms total)
[  PASSED  ] 4 tests.
/home/diego/src/kiwix-build/BUILD_native_dyn/libzim/test/cluster: error while loading shared libraries: libicudata.so.58: cannot open shared object file: No such file or directory
/home/diego/src/kiwix-build/BUILD_native_dyn/libzim/test/creator: error while loading shared libraries: libicudata.so.58: cannot open shared object file: No such file or directory
/home/diego/src/kiwix-build/BUILD_native_dyn/libzim/test/dirent: error while loading shared libraries: libicudata.so.58: cannot open shared object file: No such file or directory
/home/diego/src/kiwix-build/BUILD_native_dyn/libzim/test/header: error while loading shared libraries: libicudata.so.58: cannot open shared object file: No such file or directory
/home/diego/src/kiwix-build/BUILD_native_dyn/libzim/test/uuid: error while loading shared libraries: libicudata.so.58: cannot open shared object file: No such file or directory
/home/diego/src/kiwix-build/BUILD_native_dyn/libzim/test/template: error while loading shared libraries: libicudata.so.58: cannot open shared object file: No such file or directory
/home/diego/src/kiwix-build/BUILD_native_dyn/libzim/test/archive: error while loading shared libraries: libicudata.so.58: cannot open shared object file: No such file or directory
/home/diego/src/kiwix-build/BUILD_native_dyn/libzim/test/iterator: error while loading shared libraries: libicudata.so.58: cannot open shared object file: No such file or directory
/home/diego/src/kiwix-build/BUILD_native_dyn/libzim/test/reader: error while loading shared libraries: libicudata.so.58: cannot open shared object file: No such file or directory
[...]
```

The missing library was build:

```
(src) diego@scw-19c522:~/src/kiwix-build$ find . -name libicudata.so.58
./BUILD_native_dyn/INSTALL/lib/arm-linux-gnueabihf/libicudata.so.58
./BUILD_native_dyn/icu4c-58.2/stubdata/libicudata.so.58
./BUILD_native_dyn/icu4c-58.2/lib/libicudata.so.58
```

Thanks in advance,
  Diego.

**Comment by kelson42** [comment] 2021-06-13 12:26
Wonder is this is supported at all, maybe a duplicate of #148?

**Comment by kelson42** [comment] 2022-06-05 05:13
@diegoroversi Time has passed, are you still impacted by this problem?

**Comment by diegoroversi** [comment] 2022-06-08 05:04
I have no more access to the original server, so I started a new build from a fresh server, and I get this error:

(src) tmpinst@debian:~/src/kiwix-build$ kiwix-build 
[INSTALL PACKAGES]
 - automake : SKIP
 - libtool : SKIP
 - cmake : SKIP
 - git : SKIP
 - subversion : SKIP
 - ccache : SKIP
 - pkg-config : SKIP
 - gcc : SKIP
 - autopoint : SKIP
 - libbz2-dev : SKIP
 - libmagic-dev : SKIP
 - zlib1g-dev : SKIP
 - uuid-dev : SKIP
 - libmicrohttpd-dev : SKIP
SKIP, No package to install.
[SETUP PLATFORMS]
[PREPARE]
prepare sources pugixml :
  download pugixml : Cannot download url http://mirror.download.kiwix.org/dev/pugixml-1.2.tar.gz:
Not Found
ERROR

Stopping build due to errors

**Comment by kelson42** [comment] 2022-09-06 15:49
@diegoroversi error has been fixed. Does it compules now for you?

**Comment by kelson42** [comment] 2023-03-31 03:54
No feedback, closing

**Closed by kelson42** 2023-03-31 03:54 UTC
Labels: question
