### ISSUE TITLE
Missing macos bin in libzim 7.0.0 release

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-build#498] opened 2021-10-08 07:27 UTC
http://download.openzim.org/release/libzim/ contains the source and the `libzim_linux-x86_64-7.0.0.tar.gz` but not macOS one.

**Comment by mgautierfr** [comment] 2021-10-08 09:49
Duplicate of openzim/libzim#633

**Closed by mgautierfr** 2021-10-08 09:49 UTC
Labels: bug
