### ISSUE TITLE
Both CI and nightlies are broken since a week

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#572] opened 2023-03-08 07:38 UTC
TOP prio to fix

**Comment by mgautierfr** [comment] 2023-03-08 09:34
This is a issue with file rights when extracting base dependencies on android (https://github.com/kiwix/kiwix-build/actions/runs/4360241855/jobs/7622937519).

I was supposing it comes from you PR about reorganization of docker image (#565) but it is not merged (but it could still have uploaded archive used in other CI). The PR #565 fails for the same reason than nightlies. I don't know what is the root cause here.

**Comment by kelson42** [comment] 2023-03-11 15:37
@mgautierfr The problem seems to find its origin in the new dependence tarball. For example `base_deps2_bionic_android_arm_81.tar.xz`. See:
```
kelson@camber:/tmp$ tar -xvf base_deps2_bionic_android_arm_79.tar.xz | grep libuuid.a
BUILD_android_arm/INSTALL/lib/arm-linux-androideabi/libuuid.a
kelson@camber:/tmp$ tar -xvf base_deps2_bionic_android_arm_81.tar.xz | grep libuuid.a
BUILD_android_arm/INSTALL/lib/arm-linux-androideabi/libuuid.a
BUILD_android_arm/INSTALL/lib/arm-linux-androideabi/libuuid.a
```
The tarball extractor does not like to rewrite a file on the fs which is already there. Maybe we should allow that, but IMO it looks really dubious that we have a tarball defining twice the same file.

**Comment by Jaifroid** [comment] 2023-03-14 09:38
Additionally, although the wasm build appears to be being created correctly (it is green in the relevant CI action), and it is uploaded to nightly, in fact it doesn't contain the binary, only the includes. See #556. This is causing [CI to fail in javascript-libzim](https://github.com/openzim/javascript-libzim/actions) since 2nd March.

**Comment by rgaudin** [comment] 2023-03-18 18:14
```
Invalid workflow file: .github/workflows/releaseNigthly.yml#L69
The workflow is not valid. .github/workflows/releaseNigthly.yml (Line: 69, Col: 12): Job 'Linux' depends on unknown job 'Docker'.
```

**Closed** 2023-03-19 14:49 UTC
Labels: bug
