### ISSUE TITLE
Publish kiwix-tools for i586 and i686 archictectures

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#94] opened 2017-11-22 18:33 UTC
_From @holta on November 22, 2017 18:20_

Currently on OLPC's 32-bit XO laptops in the developing world we are using:
http://download.kiwix.org/bin/0.9/kiwix-0.9-linux-i686.tar.bz2 (30-Oct-2014)

As this is more than 3 years old and failing with new content, we're also experimenting with:
http://download.kiwix.org/bin/0.10/kiwix-0.10-linux-i686.tar.bz2 (26-Oct-2016)

With essentially all new ZIM content coming online at the end of 2017 having an internal index in the ZIM file, the above strategies are no longer working :-(

Can compiler flags hopefully be set to publish kiwix-tools (kiwix-serve, kiwix-manage) for the i686 architecture as well?  Ideally publishing to http://download.kiwix.org/nightly/ and also upholding the i686 tradition @ http://download.kiwix.org/bin/ ?

_Context: 3 million of OLPC's XO laptops were manufactured, and several 100,000 are today in active use, where Wikipedia on Kiwix is often the most adored of all apps/content when it is installed!  A special thank you to @georgejhunt & @darkenvy whose field community/integration has made this work a centerpiece in Haiti, Ghana, Mexico etc, where we distribute different versions of WikipediaFR, WikipediaHT, WikipediaEN and WikipediaES._

_Copied from original issue: kiwix/kiwix-tools#112_

**Comment by kelson42** [comment] 2017-11-22 18:33
@holta Do you have the exact models of CPUs? I remember having difficulties to make kiwix-serve working with Intel Atom devices (not supporting MMX2 instructions)?

**Comment by kelson42** [comment] 2017-11-22 18:33
@mgautierfr I suspect this should be quite easy to get nightlies compiling for i686 too?

**Comment by holta** [comment] 2017-11-22 18:56
> @holta Do you have the exact models of CPUs? I remember having difficulties to make kiwix-serve working with Intel Atom devices (not supporting MMX2 instructions)?

The most important is probably the faster CPU (almost 3 times faster since the XO-1.5 laptop was released in 2009) is the "VIA C7" which claims "Intel-compatible instruction set (including MMX, SSE, SSE2 & SSE3)" according to:
http://wiki.laptop.org/go/Hardware_specification_1.5#Core_electronics

The original XO-1 laptop (released late 2007, also important if possible) used the AMD Geode CPU LX-700 with the "i586 [Athlon] instruction set (including MMX and 3DNow! Enhanced) with additional Geode-specific instructions" according to:
http://wiki.laptop.org/go/Hardware_specification#Core_electronics
http://laptop.org/en/laptop/hardware/specs.shtml

(If more info is needed, don't hesitate to respond as @georgejhunt can help explain, Thanks!)

**Comment by kelson42** [comment] 2017-11-22 19:38
@holta It should be almost trivial IMO to get the binary for the VIA C7. More complex to get it on Geode... but doable, we need to have a look how the "old" kiwix-serve was compiled. We will try to achieve that before february 2018.

**Comment by holta** [comment] 2017-11-22 19:55
> @holta It should be almost trivial IMO to get the binary for the VIA C7. More complex to get it on Geode... but doable, we need to have a look how the "old" kiwix-serve was compiled. We will try to achieve that before february 2018.

Priceless, Profound Thanks!  February is _Black History Month_ and also _Free and Open Source Software Month_, so Haiti & beyond will be ready then for one or both i686 builds then.

**Comment by kelson42** [comment] 2017-11-27 13:16
The original ticket dealing with removal of SSE instruction was:
https://sourceforge.net/p/kiwix/bugs/478/

The original fix was in:
https://github.com/kiwix/kiwix-xulrunner/commit/4e6bd8d806eda6b1b4959259dc30a157533e2cb2

I recommend to build straight forward i686 and i585 without the SSE(2) instruction set, which means with the GCC option -mno-sse

@mgautierfr complicated?

**Comment by holta** [comment] 2018-02-21 18:07
> The original ticket dealing with removal of SSE instruction was:
https://sourceforge.net/p/kiwix/bugs/478/
>
> The original fix was in:
kiwix/kiwix-xulrunner@4e6bd8d
>
> I recommend to build straight forward i686 and i585 without the SSE(2) instruction set, which means with the GCC option -mno-sse
>
> @mgautierfr complicated?

@kelson42 is February timeframe still plausible?

This is very badly needed in Haiti, however we can hopefully get there in coming weeks !

**Comment by kelson42** [comment] 2018-02-24 17:07
@holta Things did not run like I wanted... I would recommend to find someone else to do it as we have already a really tight agenda.

**Comment by holta** [comment] 2018-02-24 17:18
> Things did not run like I wanted...

@kelson42 is it possible you could post the full gcc compiler command/options/scripts from 26-Oct-2016 (or similar) that generated http://download.kiwix.org/bin/0.10/kiwix-0.10-linux-i686.tar.bz2 ?

**Comment by kelson42** [comment] 2018-02-24 17:19
@holta This is not related at all with this ticket... but so far I know this has been done manually and this piece of software is not supported anymore.

**Comment by holta** [comment] 2018-02-24 17:47
> This is not related at all with this ticket...

Apologies I assumed http://download.kiwix.org/bin/0.10 (Oct 2016) was the predecessor to kiwix-tools, similar to http://download.kiwix.org/nightly/.  Around the time support for ZIM files with internal / full-text indexes began.

(But if I completely misunderstood the 2016-2017 roadmap/lineage, my apologies &mdash; any clarifications helpful if available!)

ASIDE: probably not worth opening a ticket, but just fyi none of the 3 kiwix-tools builds appeared in yesterday's http://download.kiwix.org/nightly/2018-02-23/

**Comment by holta** [comment] 2018-02-26 14:44
> ASIDE: probably not worth opening a ticket, but just fyi none of the 3 kiwix-tools builds appeared in yesterday's http://download.kiwix.org/nightly/2018-02-23/

Still no kiwix-tools have appeared since http://download.kiwix.org/nightly/2018-02-21/ fyi.  (Not sure if this really needs a ticket.)

**Comment by holta** [comment] 2018-03-26 17:47
Thanks to @avni who is working on trying to solve this i686 support, for OLPC XO-1.5 especially!

Excerpt of her ongoing work @ https://lists.wikimedia.org/pipermail/offline-l/2018-March/thread.html

**Comment by kelson42** [comment] 2018-03-26 18:08
kiwix-tools releases are newly published here https://download.kiwix.org/release/kiwix-tools/

**Comment by kelson42** [comment] 2018-03-28 09:01
So, @mgautierfr is going to integrate the support of the 585 arch (without SSE instructions) in the next days. It is on his TODO shortlist.

**Comment by holta** [comment] 2018-03-28 16:33
@kelson42 asked for libc version: is the following sufficient?  OLPC's OS 13.2.9 on XO-1.5 and XO-1 both show:
```
-bash-4.2# rpm -q glibc
glibc-2.16-34.olpc.0.fc18.i686
-bash-4.2# rpm -q glibc-common
glibc-common-2.16-34.olpc.0.fc18.i686
```
As reconfirmed by:

http://download.laptop.org/xo-1.5/os/official/13.2.9-21/32021o1.packages.txt
http://download.laptop.org/xo-1/os/official/13.2.9-21/32021o0.packages.txt

CLARIF: OLPC's very latest OS 13.2.9 remains built on the very old Fedora 18 (unfortunately, but this is for offline use in Haiti etc).

**Comment by avni** [comment] 2018-03-31 05:59
Hi - Please see https://github.com/kiwix/kiwix-tools/issues/170#issuecomment-376542055 for errors encountered while trying to compile libzim from source on i686 fedora18. Any help that can be provided is greatly appreciated.

**Comment by mgautierfr** [comment] 2018-04-09 13:31
I've just fix the build for i586 (without sse).
The first nightly build is available here : http://download.kiwix.org/nightly/2018-04-09/kiwix-tools_i586-2018-04-09.tar.gz

Can you test it ?
If it works for you, I will create a release with the last fixes for i586.

**Comment by kelson42** [comment] 2018-04-09 18:10
@mgautierfr File naming seems not so good to me: `2018-04-09/kiwix-tools_i586-2018-04-09.tar.gz` would be IMO advantageously replaced by `2018-04-09/kiwix-tools_linux32-2018-04-09.tar.gz`

**Comment by kelson42** [comment] 2018-04-10 04:17
@avni I think you primarely want to have kiwix-serve running. Can you try to run it: ./kiwix-serve --port=8080 your_zim_file

**Comment by kelson42** [comment] 2018-04-10 04:54
@mgautierfr We got confirmation from @holta that i586 static binaries we distribute since yesterday work fine on the OLPC. So I close that ticket. Would you please consider my comment here? https://github.com/kiwix/kiwix-build/issues/94#issuecomment-379843366. For the rest I think we should probably close that ticket.

**Comment by holta** [comment] 2018-04-10 05:33
@avni, @georgejhunt, @jvonau, @tim-moody :

Full-Text search, Title Search, and the "Random" button all work on XO-1.5 (OLPC OS 13.2.9) with modern ZIM files when I ran either:
```
./kiwix-serve --port=3000 ekopedia_fr_all_2018-04.zim
./kiwix-serve --port=3000 wikipedia_ht_all_2018-03.zim
```
This is using kiwix-serve from http://download.kiwix.org/nightly/2018-04-09/kiwix-tools_i586-2018-04-09.tar.gz

WARNING 1: autocomplete is somehow not complete with Haitian Creole, as kiwix-serve issues the following "stemming" warning when you are typing in search terms:
```
No steeming for language 'ht'
```
WARNING 2: when kiwix-serve is run from Terminal in Sugar Learning Platform's Desktop (e.g. as user "olpc") it will work initially then fail rather quickly a few minutes later, requiring a reboot or similar.  Possibly b/c the kiwix-process is being backgrounded, and becomes a zombie process of some kind when Sugar's Terminal activity is auto-backgrounded?  I could not find any such zombie processes using "ps ax" etc, so was forced to reboot :(

WHEREAS: when the above kiwix-serve commands are run as root (e.g. from Ctrl-Alt-F2) they appear to survive far longer (as we require for kids to be able to rely on this!)

_IN ANY CASE: thanks to @avni and to the entire Kiwix team for their heroic work in recent weeks &mdash; so we can now fine-tune this for reliability &mdash; starting right here with Haiti orphanages and schools._

**Comment by kelson42** [comment] 2018-04-10 06:01
@holta There is nothing we can do about W1. This is a message from Xapian/Fulltext engine. To some extend this is normal and there is nothing you should worry about.

For W2, I suspect you mean, you need to restart `kiwix-serve` (not reboot the system). if kiwix-serve crash, we need (1) the log, please start with `--verbose`  (2) the `core` file. I would then recommend to handle this in a separated ticket. I have no explanation to the difference of behaviour you report about `root` and `olpc`, please check this accurately.

**Comment by mgautierfr** [comment] 2018-05-15 16:09
kiwix-tools is published for i586 architecture. I'm closing.

**Closed by mgautierfr** 2018-05-15 16:09 UTC
Labels: enhancement, help wanted
