### ISSUE TITLE
Release publication should create a "latest" link.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#448] opened 2020-06-12 12:25 UTC
Several tools now download the build release on there CI.
When we publish a new version, we need to update the version number in those CIs.

The publication process should create/update a "latest" symlink to the last version to simplify the use of those release.

And it will be useful for all users anyway.

**Comment by kelson42** [comment] 2020-06-12 12:29
We have a permalink, take a normal link and remove the version number.

**Comment by mgautierfr** [comment] 2020-06-12 12:44
`wget https://download.openzim.org/release/libzim/libzim_linux-x86_64.tar.gz` doesn't work.

**Comment by mgautierfr** [comment] 2020-06-12 12:45
And I think that having a "real" symlink make this feature discoverable and it is used in a lot of other projects.

**Comment by kelson42** [comment] 2020-06-12 14:03
I will this

**Comment by kelson42** [comment] 2020-06-13 09:21
Done, was as well a duplicate of https://github.com/kiwix/maintenance/issues/128

**Closed** 2020-06-15 16:43 UTC
Labels: enhancement
