### ISSUE TITLE
Documentation for building custom apps

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-build#206] opened 2018-06-26 00:04 UTC
Could we put documentation for building custom apps in the readme?

**Comment by kelson42** [comment] 2018-06-26 05:13
@mhutti1 looks good to me, but we should probably get rid of the perl

**Comment by kelson42** [comment] 2018-07-13 06:05
@mgautierfr Can you help @mhutti1 please?

**Comment by mgautierfr** [comment] 2018-07-19 15:15
I've fix the compilation of android-custom-app (https://github.com/kiwix/kiwix-build/pull/224) and quickly updated the documentation ( https://github.com/kiwix/kiwix-build/wiki/Build-and-publish-a-custom-app-locally-(without-travis) ).

However, I've not totally update the documentation. I've skip the creation of multi-arch apk.
The compilation itself should work (just add several time the arch you want to support (`--android-arch arm --android-arch arm64 ...`)).
The problem come from the VERSION_CODE to use. We haven't defined a code for multi-arch apk.
- The simpler would be to use the code 6.
- The nicer would be to use the code 0 and shift all existing code (1:arm, 2:arm64, ... 6:mips_64).
  However, if we do this, the new multi-arch apk version will be inferior to old specific arch apk version.
  In this case, google play will probably not update the user apk, and the user may have to remove the application and install it again (I'm not sure about that, having an android/googleplay expert advice would be nice).

**Comment by mhutti1** [comment] 2018-07-19 22:07
```
kiwix-build kiwix-android-custom --android-arch arm --android-custom-app wikimed_mini --zim-file-url "http://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_nodet_2017-08.zim"
```
Gives

```
[INSTALL PACKAGES]
 - automake : SKIP
 - libtool : SKIP
 - cmake : SKIP
 - git : SKIP
 - subversion : SKIP
 - ccache : SKIP
 - pkg-config : SKIP
 - gcc : SKIP
 - autopoint : SKIP
 - libbz2-dev : SKIP
 - libmagic-dev : SKIP
 - libctpp2-dev : SKIP
 - ctpp2-utils : SKIP
 - zlib1g-dev : SKIP
 - uuid-dev : SKIP
SKIP, No package to install.
[SETUP PLATFORMS]
[PREPARE]
prepare sources kiwix-android :
  gitclone kiwix-android : OK
  gitupdate kiwix-android : OK
prepare sources pugixml :
  download pugixml : SKIP
  extract pugixml : SKIP
  patch pugixml : SKIP
prepare sources lzma :
  download lzma : SKIP
  extract lzma : SKIP
prepare sources xapian-core :
  download xapian-core : SKIP
  extract xapian-core : SKIP
  patch xapian-core : SKIP
prepare sources icu4c :
  download icu4c : SKIP
  extract icu4c : SKIP
  patch icu4c : SKIP
prepare sources libzim :
  gitclone libzim : SKIP
  gitupdate libzim : OK
prepare sources libaria2 :
  download libaria2 : SKIP
  extract libaria2 : SKIP
  patch libaria2 : SKIP
  post_prepare_script libaria2 : SKIP
prepare sources kiwix-lib :
  gitclone kiwix-lib : SKIP
  gitupdate kiwix-lib : OK
prepare sources kiwix-android-custom :
  gitclone kiwix-android-custom : OK
  gitupdate kiwix-android-custom : OK
[BUILD]
build kiwix-android (native_dyn):
SKIP
build pugixml (native_dyn):
  configure pugixml : OK
  compile pugixml : OK
  test pugixml : OK
  install pugixml : OK
build lzma (native_dyn):
  configure lzma : OK
  compile lzma : OK
  install lzma : OK
build xapian-core (native_dyn):
  configure xapian-core : OK
  compile xapian-core : .OK
  install xapian-core : OK
build icu4c (native_dyn):
  configure icu4c : OK
  compile icu4c : ..OK
  install icu4c : OK
build libzim (native_dyn):
  configure libzim : OK
  compile libzim : OK
  test libzim : OK
  install libzim : OK
build libaria2 (native_dyn):
  configure libaria2 : OK
  compile libaria2 : ...OK
  install libaria2 : OK
build kiwix-lib (native_dyn):
  configure kiwix-lib : OK
  compile kiwix-lib : OK
  test kiwix-lib : OK
  install kiwix-lib : OK
build kiwix-android-custom (native_dyn):
  configure kiwix-android-custom : OK
  download_zim kiwix-android-custom : ERROR
Traceback (most recent call last):
  File "/usr/local/bin/kiwix-build", line 9, in <module>
    load_entry_point('kiwix-build==0.1', 'console_scripts', 'kiwix-build')()
  File "/usr/local/lib/python3.5/dist-packages/kiwixbuild/__init__.py", line 84, in main
    builder.run()
  File "/usr/local/lib/python3.5/dist-packages/kiwixbuild/builder.py", line 200, in run
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/kiwixbuild/builder.py", line 126, in build
    builder.build()
  File "/usr/local/lib/python3.5/dist-packages/kiwixbuild/dependencies/kiwix_custom_app.py", line 59, in build
    self.command('download_zim', self._download_zim)
  File "/usr/local/lib/python3.5/dist-packages/kiwixbuild/dependencies/base.py", line 227, in command
    ret = function(*args, context=context)
  File "/usr/local/lib/python3.5/dist-packages/kiwixbuild/dependencies/kiwix_custom_app.py", line 72, in _download_zim
    self.buildEnv.download(zim_file)
AttributeError: 'BuildEnv' object has no attribute 'download'
```

**Comment by mhutti1** [comment] 2018-07-19 23:36
Can confirm it will work if you use a ZIM file size not a URL. Not had time to test with an actual ZIM file though.

**Comment by mgautierfr** [comment] 2018-08-20 09:11
The problem is indeed that it try to compile everything on `native_dyn` instead of `android_arm` and `android`

For now the default platform is `native_dyn` for all project and `android` for android project. It should be `android` for `android` and `kiwix-android-custom` custom. I will fix this.

You can explicitly set the target platform using the option `--target-platform`.
`kiwix-build kiwix-android-custom --target-platform android --android-arch arm --android-custom-app wikimed_mini --zim-file-size 100` should work

**Closed** 2018-08-20 15:53 UTC
Labels: enhancement, question
