### ISSUE TITLE
Error building custom app via Travis script

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-build#146] opened 2018-04-07 20:18 UTC
./build_custom_app.py --custom-app=wikimedes --travis-token=************************
Try to get package name from info.json file
Try to get zim url from info.json file
Try to get version_name form info.json file
Found package_name 'org.kiwix.kiwixcustomwikimedes'
Found zim_url 'https://download.kiwix.org/zim/wikipedia_es_medicine.zim'
Found version_name '2016-09'
Try to get zim size
Zim size is 597702
Request 111081550 has been schedule.
Try to get associated build.
Cannot find build. Wait 1 second and try again
10 tries left
Try to get associated build.
Cannot find build. Wait 1 second and try again
9 tries left
Try to get associated build.
Cannot find build. Wait 1 second and try again
8 tries left
Try to get associated build.
Cannot find build. Wait 1 second and try again
7 tries left
Try to get associated build.
Cannot find build. Wait 1 second and try again
6 tries left
Try to get associated build.
Cannot find build. Wait 1 second and try again
5 tries left
Try to get associated build.
Cannot find build. Wait 1 second and try again
4 tries left
Try to get associated build.
Cannot find build. Wait 1 second and try again
3 tries left
Try to get associated build.
Cannot find build. Wait 1 second and try again
2 tries left
Try to get associated build.
Cannot find build. Wait 1 second and try again
1 tries left
Request has been accepted by travis-ci but I cannot found the associated build. Have a look here https://travis-ci.org/kiwix/kiwix-build/buildsif you found it.
Travis build has been launch.

Build does not appear.

**Comment by kelson42** [comment] 2018-04-07 20:29
I suspect this is a duplicate of https://github.com/kiwix/kiwix-build/issues/59

**Comment by mhutti1** [comment] 2018-04-10 15:10
I don't know if this is a duplicate myself? Your issue seems to be more specific than mine but it might be the cause of this issue. I don't know. If you think it is then go ahead and close this.

**Comment by kelson42** [comment] 2019-06-27 18:17
Custom app CI+publication will be handle within 3.0 milestone

**Comment by kelson42** [comment] 2019-12-05 13:28
We don't build Kiwix Android (custom apps) with Kiwix build.

**Closed by kelson42** 2019-12-05 13:28 UTC
